spring.application.name=user-service
server.port=${USER_SERVICE_PORT:8083}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/myrealm}

app.keycloak.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8180}
app.keycloak.realm=${KEYCLOAK_REALM:myrealm}
app.keycloak.client-id=${KEYCLOAK_CLIENT_ID:admin-cli}
app.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:7sZWo3AhnxRZoDMDcI5oSpVbdtDtoJ9n}

app.keycloak.admin-realm=${KEYCLOAK_ADMIN_REALM:master}
app.keycloak.admin-client-id=${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
app.keycloak.admin-client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:}
app.keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME:admin}
app.keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD:admin}
