-- Création de la table DISPONIBILITE si elle n'existe pas
CREATE TABLE IF NOT EXISTS DISPONIBILITE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BUDDY_PAIR_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    DEBUT TIMESTAMP NOT NULL,
    FIN TIMESTAMP NOT NULL
);

-- Index pour optimiser les recherches
CREATE INDEX IF NOT EXISTS IDX_DISPONIBILITE_BUDDY_PAIR ON DISPONIBILITE(BUDDY_PAIR_ID);
CREATE INDEX IF NOT EXISTS IDX_DISPONIBILITE_USER ON DISPONIBILITE(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_DISPONIBILITE_PERIODE ON DISPONIBILITE(DEBUT, FIN);

-- Vérification de la table
SELECT * FROM DISPONIBILITE;
