apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamesback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamesback
  template:
    metadata:
      labels:
        app: gamesback
    spec:
      containers:
        - name: gamesback
          image: gamesback-test:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-games:3306/games_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: gamesback
spec:
  selector:
    app: gamesback
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP