# Utilisé par sonar-scanner CLI si vous préférez l’outil natif au lieu de « mvn sonar:sonar ».
sonar.projectKey=gestioncours
sonar.projectName=GestionCours
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
