spring.application.name=ApiGateway
server.port=8087

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Spring Cloud Gateway Routes
spring.cloud.gateway.routes[0].id=onlinecourses-route
spring.cloud.gateway.routes[0].uri=lb://GestionCours
spring.cloud.gateway.routes[0].predicates[0]=Path=/onlinecourses/**

spring.cloud.gateway.routes[1].id=onsitecourses-route
spring.cloud.gateway.routes[1].uri=lb://GestionCours
spring.cloud.gateway.routes[1].predicates[0]=Path=/onsitecourses/**